[build]
  command = "node netlify/functions/build-index.js"
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Access-Control-Allow-Origin = "*"
